# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c99e8fbb3d397b3236d56bc367ebce4d43180f0401e823a7fd195fcc5cd331f3a42cdbff221e9cc56225881b52755eac17253e28ff13900f0bc1ea73ada75a6d

test:
  secret_key_base: e68edf3ba8ca1861bd0eab3f909d422b6f802e823cfbef0f885f07360c208387a26eed5e41f24d6c741722d1909ac6032bc1bc62ca667f5013d2e12bf8ece337

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
